# ABI-DAGAR run for the matched-MCMC benchmark

This notebook applies the frozen ABI posterior operator to the fixed held-out bank used by the prior- and construction-matched MCMC experiment. It saves parameter summaries, edge-level boundary probabilities, runtime, and compressed posterior draws.

In [1]:
from pathlib import Path
import os
import sys

from IPython.display import display

def find_repository_root(start=None):
    current = (Path.cwd() if start is None else Path(start)).resolve()
    for candidate in (current, *current.parents):
        marker = candidate / 'Simulation Experiments' / 'ABI_vs_matched_MCMC' / 'matched_abi_runner.py'
        if marker.exists():
            return candidate
    raise FileNotFoundError('Could not locate the ABI_poisson_regression repository root.')

REPOSITORY_ROOT = find_repository_root()
EXPERIMENT_DIR = REPOSITORY_ROOT / 'Simulation Experiments' / 'ABI_vs_matched_MCMC'
if str(EXPERIMENT_DIR) not in sys.path:
    sys.path.insert(0, str(EXPERIMENT_DIR))

from matched_abi_runner import run_abi_benchmark

BENCHMARK_DIR = EXPERIMENT_DIR / 'datasets' / 'benchmark_bank_seed123_n100'
RESULTS_DIR = Path(os.environ.get(
    'ABI_MATCHED_ABI_RESULTS_DIR', BENCHMARK_DIR / 'abi_results_all100'
))
CHECKPOINT = Path(os.environ.get(
    'ABI_MATCHED_CHECKPOINT', REPOSITORY_ROOT / 'Training' / 'Checkpoints' / 'poisson_dagar.keras'
))
NUM_SAMPLES = int(os.environ.get('ABI_MATCHED_NUM_SAMPLES', '10000'))
SEED = 123
DATASET_IDS = None
MAX_DATASETS_ENV = os.environ.get('ABI_MATCHED_MAX_DATASETS')
MAX_DATASETS = int(MAX_DATASETS_ENV) if MAX_DATASETS_ENV else None
SAVE_DRAWS = True
QUIET = False

BENCHMARK_DIR, RESULTS_DIR, CHECKPOINT

(WindowsPath('C:/Dati/Lavori/Aiello_Banerjee_2026/Code/ABI_poisson_regression/Simulation Experiments/ABI_vs_matched_MCMC/datasets/benchmark_bank_seed123_n100'),
 WindowsPath('C:/Dati/Lavori/Aiello_Banerjee_2026/Code/ABI_poisson_regression/Simulation Experiments/ABI_vs_matched_MCMC/datasets/benchmark_bank_seed123_n100/abi_results_all100'),
 WindowsPath('C:/Dati/Lavori/Aiello_Banerjee_2026/Code/ABI_poisson_regression/Training/Checkpoints/poisson_dagar.keras'))

## Run the frozen posterior operator

In [2]:
outputs = run_abi_benchmark(
    benchmark_dir=BENCHMARK_DIR,
    results_dir=RESULTS_DIR,
    checkpoint=CHECKPOINT,
    num_samples=NUM_SAMPLES,
    seed=SEED,
    dataset_ids=DATASET_IDS,
    max_datasets=MAX_DATASETS,
    save_draws=SAVE_DRAWS,
    quiet=QUIET,
)

display(outputs['parameter_df'].head())
display(outputs['edge_metrics_df'].head())
display(outputs['runtime_df'].head())

INFO:bayesflow:Using backend 'tensorflow'

Loading ABI checkpoint: C:\Dati\Lavori\Aiello_Banerjee_2026\Code\ABI_poisson_regression\Training\Checkpoints\poisson_dagar.keras

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

[1/100] Running ABI for dataset_0000 (N=58, edges=161)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[2/100] Running ABI for dataset_0001 (N=85, edges=242)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[3/100] Running ABI for dataset_0002 (N=168, edges=490)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[4/100] Running ABI for dataset_0003 (N=132, edges=381)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[5/100] Running ABI for dataset_0004 (N=219, edges=638)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[6/100] Running ABI for dataset_0005 (N=208, edges=606)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[7/100] Running ABI for dataset_0006 (N=100, edges=284)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[8/100] Running ABI for dataset_0007 (N=68, edges=191)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[9/100] Running ABI for dataset_0008 (N=203, edges=594)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[10/100] Running ABI for dataset_0009 (N=148, edges=429)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[11/100] Running ABI for dataset_0010 (N=47, edges=130)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[12/100] Running ABI for dataset_0011 (N=147, edges=426)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[13/100] Running ABI for dataset_0012 (N=287, edges=841)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[14/100] Running ABI for dataset_0013 (N=162, edges=470)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[15/100] Running ABI for dataset_0014 (N=92, edges=262)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[16/100] Running ABI for dataset_0015 (N=81, edges=227)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[17/100] Running ABI for dataset_0016 (N=179, edges=523)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[18/100] Running ABI for dataset_0017 (N=88, edges=249)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[19/100] Running ABI for dataset_0018 (N=146, edges=422)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[20/100] Running ABI for dataset_0019 (N=251, edges=734)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[21/100] Running ABI for dataset_0020 (N=186, edges=541)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[22/100] Running ABI for dataset_0021 (N=135, edges=391)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[23/100] Running ABI for dataset_0022 (N=214, edges=621)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[24/100] Running ABI for dataset_0023 (N=151, edges=437)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[25/100] Running ABI for dataset_0024 (N=228, edges=664)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[26/100] Running ABI for dataset_0025 (N=76, edges=215)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[27/100] Running ABI for dataset_0026 (N=79, edges=223)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[28/100] Running ABI for dataset_0027 (N=255, edges=746)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[29/100] Running ABI for dataset_0028 (N=165, edges=480)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[30/100] Running ABI for dataset_0029 (N=136, edges=396)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[31/100] Running ABI for dataset_0030 (N=139, edges=401)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[32/100] Running ABI for dataset_0031 (N=260, edges=764)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[33/100] Running ABI for dataset_0032 (N=262, edges=770)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[34/100] Running ABI for dataset_0033 (N=210, edges=614)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[35/100] Running ABI for dataset_0034 (N=232, edges=676)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[36/100] Running ABI for dataset_0035 (N=153, edges=445)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[37/100] Running ABI for dataset_0036 (N=192, edges=553)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[38/100] Running ABI for dataset_0037 (N=180, edges=522)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[39/100] Running ABI for dataset_0038 (N=160, edges=464)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[40/100] Running ABI for dataset_0039 (N=74, edges=207)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[41/100] Running ABI for dataset_0040 (N=137, edges=394)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[42/100] Running ABI for dataset_0041 (N=274, edges=803)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[43/100] Running ABI for dataset_0042 (N=48, edges=132)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[44/100] Running ABI for dataset_0043 (N=224, edges=654)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[45/100] Running ABI for dataset_0044 (N=212, edges=617)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[46/100] Running ABI for dataset_0045 (N=81, edges=231)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[47/100] Running ABI for dataset_0046 (N=53, edges=143)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[48/100] Running ABI for dataset_0047 (N=123, edges=353)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[49/100] Running ABI for dataset_0048 (N=74, edges=209)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[50/100] Running ABI for dataset_0049 (N=170, edges=493)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[51/100] Running ABI for dataset_0050 (N=84, edges=232)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[52/100] Running ABI for dataset_0051 (N=233, edges=683)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[53/100] Running ABI for dataset_0052 (N=189, edges=551)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[54/100] Running ABI for dataset_0053 (N=168, edges=486)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[55/100] Running ABI for dataset_0054 (N=87, edges=242)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[56/100] Running ABI for dataset_0055 (N=146, edges=426)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[57/100] Running ABI for dataset_0056 (N=205, edges=597)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[58/100] Running ABI for dataset_0057 (N=123, edges=357)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[59/100] Running ABI for dataset_0058 (N=251, edges=736)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[60/100] Running ABI for dataset_0059 (N=293, edges=864)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[61/100] Running ABI for dataset_0060 (N=188, edges=547)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[62/100] Running ABI for dataset_0061 (N=187, edges=544)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[63/100] Running ABI for dataset_0062 (N=195, edges=565)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[64/100] Running ABI for dataset_0063 (N=271, edges=793)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[65/100] Running ABI for dataset_0064 (N=271, edges=797)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[66/100] Running ABI for dataset_0065 (N=58, edges=162)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[67/100] Running ABI for dataset_0066 (N=149, edges=435)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[68/100] Running ABI for dataset_0067 (N=67, edges=189)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[69/100] Running ABI for dataset_0068 (N=102, edges=289)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[70/100] Running ABI for dataset_0069 (N=136, edges=392)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[71/100] Running ABI for dataset_0070 (N=246, edges=724)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[72/100] Running ABI for dataset_0071 (N=284, edges=837)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[73/100] Running ABI for dataset_0072 (N=176, edges=513)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[74/100] Running ABI for dataset_0073 (N=255, edges=745)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[75/100] Running ABI for dataset_0074 (N=109, edges=311)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[76/100] Running ABI for dataset_0075 (N=299, edges=884)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[77/100] Running ABI for dataset_0076 (N=239, edges=700)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[78/100] Running ABI for dataset_0077 (N=61, edges=169)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[79/100] Running ABI for dataset_0078 (N=211, edges=614)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[80/100] Running ABI for dataset_0079 (N=83, edges=232)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[81/100] Running ABI for dataset_0080 (N=165, edges=479)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[82/100] Running ABI for dataset_0081 (N=267, edges=783)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[83/100] Running ABI for dataset_0082 (N=146, edges=426)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[84/100] Running ABI for dataset_0083 (N=67, edges=189)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[85/100] Running ABI for dataset_0084 (N=187, edges=543)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[86/100] Running ABI for dataset_0085 (N=62, edges=171)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[87/100] Running ABI for dataset_0086 (N=300, edges=879)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[88/100] Running ABI for dataset_0087 (N=117, edges=334)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[89/100] Running ABI for dataset_0088 (N=233, edges=682)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[90/100] Running ABI for dataset_0089 (N=289, edges=850)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[91/100] Running ABI for dataset_0090 (N=63, edges=173)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[92/100] Running ABI for dataset_0091 (N=253, edges=744)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[93/100] Running ABI for dataset_0092 (N=269, edges=789)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[94/100] Running ABI for dataset_0093 (N=50, edges=137)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[95/100] Running ABI for dataset_0094 (N=187, edges=544)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[96/100] Running ABI for dataset_0095 (N=188, edges=550)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[97/100] Running ABI for dataset_0096 (N=150, edges=437)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[98/100] Running ABI for dataset_0097 (N=234, edges=679)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[99/100] Running ABI for dataset_0098 (N=231, edges=674)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

[100/100] Running ABI for dataset_0099 (N=237, edges=696)

Sampling:   0%|          | 0/1 [00:00<?, ?batch/s]

Saved ABI benchmark outputs to: C:\Dati\Lavori\Aiello_Banerjee_2026\Code\ABI_poisson_regression\Simulation Experiments\ABI_vs_matched_MCMC\datasets\benchmark_bank_seed123_n100\abi_results_all100

,dataset_id,parameter,posterior_mean,posterior_sd,posterior_median,lower_95,upper_95,truth,bias_mean,abs_error_mean,covered_95
0,dataset_0000,beta0,-0.709619,0.072406,-0.711638,-0.807672,-0.617500,-0.685540,-0.024079,0.024079,1
1,dataset_0000,sigma2_w,0.391629,0.174728,0.348860,0.187546,0.867136,0.181137,0.210493,0.210493,0
2,dataset_0000,eta_raw,0.319897,0.243645,0.258186,0.014033,0.933616,0.569412,-0.249516,0.249516,1
3,dataset_0000,eta,0.207372,0.157942,0.167368,0.009097,0.605212,0.369119,-0.161747,0.161747,1
4,dataset_0000,rho,0.289253,0.181949,0.257162,0.023077,0.706689,0.186174,0.103079,0.103079,1

,dataset_id,edge_count,true_boundary_count,posterior_boundary_count_mpm,auroc,average_precision,brier,sensitivity_mpm,specificity_mpm,boundary_count_mean_draws,boundary_count_lower_95,boundary_count_upper_95,boundary_count_truth_in_95
0,dataset_0000,161,33,0,1.0,1.0,0.111054,0.000000,1.000000,12.8478,0.0,75.000,1
1,dataset_0001,242,121,76,1.0,1.0,0.136002,0.628099,1.000000,71.0112,0.0,117.000,0
2,dataset_0002,490,8,4,1.0,1.0,0.017620,0.500000,1.000000,30.4936,0.0,157.000,1
3,dataset_0003,381,158,163,1.0,1.0,0.016915,1.000000,0.977578,160.9913,103.0,189.000,1
4,dataset_0004,638,148,39,1.0,1.0,0.105438,0.263514,1.000000,55.3416,0.0,194.025,1

,dataset_id,elapsed_sec,n_saved_draws,seconds_per_saved_draw,seconds_per_1000_saved_draws
0,dataset_0000,0.770496,10000,0.000077,0.077050
1,dataset_0001,0.843162,10000,0.000084,0.084316
2,dataset_0002,1.388843,10000,0.000139,0.138884
3,dataset_0003,1.014302,10000,0.000101,0.101430
4,dataset_0004,0.749340,10000,0.000075,0.074934